'use strict'
export const FETCH_TAGS_REQUEST = 'FETCH_TAGS_REQUEST'
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS'
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE'

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'

export const FETCH_ARTICLE_REQUEST = 'FETCH_ARTICLE_REQUEST'
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS'
export const FETCH_ARTICLE_FAILURE = 'FETCH_ARTICLE_FAILURE'

export const FETCH_RELATED_ARTICLES_REQUEST = 'FETCH_RELATED_ARTICLES_REQUEST'
export const FETCH_RELATED_ARTICLES_SUCCESS = 'FETCH_RELATED_ARTICLES_SUCCESS'
export const FETCH_RELATED_ARTICLES_FAILURE = 'FETCH_RELATED_ARTICLES_FAILURE'

export const FETCH_ARTICLES_BY_GROUP_UUID_REQUEST = 'FETCH_ARTICLES_BY_GROUP_UUID_REQUEST'
export const FETCH_ARTICLES_BY_GROUP_UUID_SUCCESS = 'FETCH_ARTICLES_BY_GROUP_UUID_SUCCESS'
export const FETCH_ARTICLES_BY_GROUP_UUID_FAILURE = 'FETCH_ARTICLES_BY_GROUP_UUID_FAILURE'

export const FETCH_FEATURE_ARTICLES_REQUEST = 'FETCH_FEATURE_ARTICLES_REQUEST'
export const FETCH_FEATURE_ARTICLES_SUCCESS = 'FETCH_FEATURE_ARTICLES_SUCCESS'
export const FETCH_FEATURE_ARTICLES_FAILURE = 'FETCH_FEATURE_ARTICLES_FAILURE'

export const FETCH_INDEX_ARTICLES_REQUEST = 'FETCH_INDEX_ARTICLES_REQUEST'
export const FETCH_SECTIONS_FEATURED_SUCCESS = 'FETCH_SECTIONS_FEATURED_SUCCESS'
export const FETCH_SECTIONS_FEATURED_FAILURE = 'FETCH_SECTIONS_FEATURED_FAILURE'
export const FETCH_LATEST_POSTS_SUCCESS = 'FETCH_LATEST_POSTS_SUCCESS'
export const FETCH_LATEST_POSTS_FAILURE = 'FETCH_LATEST_POSTS_FAILURE'
export const FETCH_CHOICES_SUCCESS = 'FETCH_CHOICES_SUCCESS'
export const FETCH_CHOICES_FAILURE = 'FETCH_CHOICES_FAILURE'
export const FETCH_INDEX_ARTICLES_FAILURE = 'FETCH_INDEX_ARTICLES_FAILURE'


export const SET_PROGRESS_PRECENTAGE = 'SET_PROGRESS_PRECENTAGE'
export const SET_PAGE_TYPE = 'SET_PAGE_TYPE'
export const SET_PAGE_TITLE = 'SET_PAGE_TITLE'
export const SET_ARTICLE_TOPIC_LIST = 'SET_ARTICLE_TOPIC_LIST'

export const FETCH_SECTION_LIST_SUCCESS = 'FETCH_SECTION_LIST_SUCCESS'
export const FETCH_SECTION_LIST_REQUEST = 'FETCH_SECTION_LIST_REQUEST'
export const FETCH_SECTION_LIST_FAILURE = 'FETCH_SECTION_LIST_FAILURE'

export const FETCH_SEARCH_RESULT_REQUEST = 'FETCH_SEARCH_RESULT_REQUEST'
export const FETCH_SEARCH_RESULT_SUCCESS = 'FETCH_SEARCH_RESULT_SUCCESS'
export const FETCH_SEARCH_RESULT_FAILURE = 'FETCH_SEARCH_RESULT_FAILURE'

export const FETCH_YOUTUBE_PLAYLIST_REQUEST = 'FETCH_YOUTUBE_PLAYLIST_REQUEST'
export const FETCH_YOUTUBE_PLAYLIST_SUCCESS = 'FETCH_YOUTUBE_PLAYLIST_SUCCESS'
export const FETCH_YOUTUBE_PLAYLIST_FAILURE = 'FETCH_YOUTUBE_PLAYLIST_FAILURE'

export const FETCH_EVENT_REQUEST = 'FETCH_EVENT_REQUEST'
export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS'
export const FETCH_EVENT_FAILURE = 'FETCH_EVENT_FAILURE'

export const FETCH_TOPICS_REQUEST = 'FETCH_TOPICS_REQUEST'
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS'
export const FETCH_TOPICS_FAILURE = 'FETCH_TOPICS_FAILURE'

export const FETCH_TOPIC_REQUEST = 'FETCH_TOPIC_REQUEST'
export const FETCH_TOPIC_SUCCESS = 'FETCH_TOPIC_SUCCESS'
export const FETCH_TOPIC_FAILURE = 'FETCH_TOPIC_FAILURE'

export const FETCH_IMAGES_REQUEST = 'FETCH_IMAGES_REQUEST'
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS'
export const FETCH_IMAGES_FAILURE = 'FETCH_IMAGES_FAILURE'

export const FETCH_AUDIOS_REQUEST = 'FETCH_AUDIOS_REQUEST'
export const FETCH_AUDIOS_SUCCESS = 'FETCH_AUDIOS_SUCCESS'
export const FETCH_AUDIOS_FAILURE = 'FETCH_AUDIOS_FAILURE'

export const PASS_ANSWER_REQUEST = 'PASS_ANSWER_REQUEST'
export const PASS_ANSWER_SUCCESS = 'PASS_ANSWER_SUCCESS'
export const PASS_ANSWER_FAILURE = 'PASS_ANSWER_FAILURE'

export const FETCH_QUESTIONNAIRE_REQUEST = 'FETCH_QUESTIONNAIRE_REQUEST'
export const FETCH_QUESTIONNAIRE_SUCCESS = 'FETCH_QUESTIONNAIRE_SUCCESS'
export const FETCH_QUESTIONNAIRE_FAILURE = 'FETCH_QUESTIONNAIRE_FAILURE'

export const RESET_QUESTIONNAIRE_REQUEST = 'RESET_QUESTIONNAIRE_REQUEST'
export const RESET_QUESTIONNAIRE_SUCCESS = 'RESET_QUESTIONNAIRE_SUCCESS'
export const RESET_QUESTIONNAIRE_FAILURE = 'RESET_QUESTIONNAIRE_FAILURE'

export const GO_NEXT_QUESTION_REQUEST = 'GO_NEXT_QUESTION_REQUEST'
export const GO_NEXT_QUESTION_SUCCESS = 'GO_NEXT_QUESTION_SUCCESS'
export const GO_NEXT_QUESTION_FAILURE = 'GO_NEXT_QUESTION_FAILURE'
